DATA:
  CROP_RESOLUTION: (1024, 2048)
  SCALE: 1.0
  DATASET: "cityscapes"
TRAINING:
  BATCH_SIZE: 16
  VAL_EVERY_N_STEPS: 50
  ADAMW:
    LEARNING_RATE: 0.00001
SYSTEM:
  NUM_WORKERS: 8
AUGMENTATION:
  COPY_PASTE: True
SELF_TRAINING:
  CONFIDENCE_STEP: 0.05
  ROUND_STEPS: 500
  ROUNDS: 3
  USE_DROP_LOSS: False
MODEL:
  TTA_INFERENCE_CONFIDENCE_THRESHOLD: 0.7
